module.exports = {
    GET_HOME_LIST: 'GET_HOME_LIST',
    GET_PRODUCT_LIST: 'GET_PRODUCT_LIST',
    GET_RECEIPE_LIST: 'GET_RECEIPE_LIST',

    SHOW_FILTER_MODAL: 'SHOW_FILTER_MODAL',
    SET_USER_LOCATION: 'SET_USER_LOCATION',
    SEARCH_HOME: 'SEARCH_HOME',

    VIEW_PROFILE: 'VIEW_PROFILE',

    RESET_HOME_LIST: 'RESET_HOME_LIST',
    RESET_PRODUCT_LIST: 'RESET_PRODUCT_LIST',
    RESET_RECEIPE_LIST: 'RESET_RECEIPE_LIST',
    RESET_PROFILE: 'RESET_PROFILE',

    CARD_LIST: 'CARD_LIST',
    ORDER_LIST: 'ORDER_LIST',

    GET_CART_DATA: 'GET_CART_DATA'


}